import { Box, Text, Grid, GridItem, Input, Button, useQuery } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useEffect } from "react";
import { useRouter } from 'next/router'
import axios from "axios";

const Id: NextPage = () => {
    const router = useRouter()
    const { id } = router.query

    useEffect(() => {
        const getRedirection = async () => {
            if (id) {
                try {
                    const response = await axios.get(`/api/getShortenedUrl/${id}`);
                    window.location.href = response.data.result.url;
                } catch (error) {
                    console.log(error)
                }
            }
        }

        getRedirection()
    }, [id])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Box backgroundColor="default.zinc" minH="100vh" color="default.white" px="36" pt="10" pb="20">
                <p>Post: {id}</p>
            </Box>
        </div >
    )
}

export async function getServerSideProps(context: any) {
    try { 
        const response = await axios.get(`/api/getShortenedUrl/${context.params.id}`);
        window.location.href = response.data.result.url;
    } catch (error) {
        console.log(error)
    }
    return { props: { "": "" } }
}

export default Id
