import { Box, Text, Grid, GridItem, Input, Button } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"


const mockUrls = [
  {
    url: "https://google.com",
    shortened: "https://encurtador/Ax3A9t"
  },
  {
    url: "https://google.com",
    shortened: "https://encurtador/Ax3A9t"
  },
  {
    url: "https://google.com",
    shortened: "https://encurtador/Ax3A9t"
  },
  {
    url: "https://google.com",
    shortened: "https://encurtador/Ax3A9t"
  }
]

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Box backgroundColor="default.zinc" h="100%" color="default.white" px="36" pt="10" pb="20">
        <Box maxWidth="1000px" margin="0 auto">

          <Box as="header">
            <Text fontSize="2xl" fontWeight="thin">ENCURTADOR</Text>
          </Box>

          <Box as="main" mt="28">
            <Grid gap="10" gridTemplateColumns={["1fr", "1fr 1fr"]}>
              <GridItem display="flex" justifyContent="center">
                <Text fontSize="5xl" mt="10" fontWeight="bold" textTransform="uppercase" marginTop="28" >Encurte seu link de maneira <Text as="span" color="default.primary">rápida</Text>  e <Text as="span" color="default.primary">fácil</Text>!</Text>
              </GridItem>
              <GridItem justifyContent="center">
                <Image src="/hero.svg" width="473" height="394" />
              </GridItem>
            </Grid>
          </Box>


          <Box as="section">
            <Box backgroundColor="default.blue" mt="20" width="100%" height="100" borderRadius="10" display="flex" justifyContent="space-between" alignItems="center" px="10">
              <Input placeholder="Escreva sua url aqui..." width="70%" height="49px" backgroundColor="default.white" color="default.zinc"></Input>
              <Button backgroundColor="default.primary" width="144px" height="49px">Encurtar</Button>
            </Box>
          </Box>

          <Box as="section">
            {mockUrls.map((url, index) => {
              return (
                <Box key={index} backgroundColor="default.white" color="default.zinc" mt="5" width="100%" height="45px" borderRadius="6" display="flex" justifyContent="space-between" alignItems="center" px="10">
                  <Text fontWeight="semibold">{url.url}</Text>
                  <Box display="flex" alignItems="center">
                    <Text mr="5" fontWeight="bold" color="default.primary">{url.shortened}</Text>
                    <Button backgroundColor="default.primary" width="100px" height="32px" color="default.white">Copiar</Button>
                  </Box>
                </Box>
              )
            })}

          </Box>
        </Box>
      </Box>
    </div >
  )
}

export default Home
